env:
  global:
    - LC_CTYPE=en_US.UTF-8

matrix:
  include:
    - os: osx
      osx_image: xcode10
      language: objective-c
      script:
        - set -o pipefail
        - xcodebuild build-for-testing test-without-building -workspace 'TryParsec.xcworkspace' -scheme 'TryParsec' -destination 'platform=OS X' ENABLE_TESTABILITY=YES | xcpretty
      env:
        - JOB=xcodebuild-macOS

    - os: osx
      osx_image: xcode10
      language: objective-c
      script:
        - set -o pipefail
        - xcodebuild build-for-testing test-without-building -workspace 'TryParsec.xcworkspace' -scheme 'TryParsec' -destination 'platform=iOS Simulator,name=iPhone 6s' ENABLE_TESTABILITY=YES | xcpretty
      env:
        - JOB=xcodebuild-iOS

    - os: osx
      osx_image: xcode10
      language: objective-c
      script:
        - set -o pipefail
        - xcodebuild build-for-testing test-without-building -workspace 'TryParsec.xcworkspace' -scheme 'TryParsec' -destination 'platform=tvOS Simulator,name=Apple TV 1080p' ENABLE_TESTABILITY=YES | xcpretty
      env:
        - JOB=xcodebuild-tvOS

    - os: osx
      osx_image: xcode10
      language: objective-c
      script:
        - set -o pipefail
        - xcodebuild build -workspace 'TryParsec.xcworkspace' -scheme 'TryParsec' -destination 'platform=watchOS Simulator,name=Apple Watch - 38mm' | xcpretty
      env:
        - JOB=xcodebuild-watchOS

    # - os: osx
    #   osx_image: xcode10
    #   script:
    #     - pod lib lint --allow-warnings
    #   env: JOB=pod-lint

    - os: osx
      osx_image: xcode10
      language: generic
      script:
        - swift build
        #- swift test
      env: JOB=swift-build-mac

    - os: linux
      language: generic
      sudo: required
      dist: trusty
      before_install:
        - eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)"
      script:
        - swift build
        #- swift test
      env: JOB=swift-build-linux
